### ISSUE TITLE
Importing ABC from collections module is removed in Python 3.9

### ISSUE THREAD

**Issue by tirkarthi** [benoitc/http-parser#84]
Importing ABC from collections module directly is removed in Python 3.9 . Import from collections.abc module instead. Similar to other Python 2/3 compatible changes in util.py this could also be fixed. Thanks for the library!

https://github.com/benoitc/http-parser/blob/2306df28fbd7946036a2609776a77833f5dda81e/http_parser/util.py#L8

**Comment by hugovk** [comment]
Please see PR https://github.com/benoitc/http-parser/issues/86.
